openapi: 3.0.3
info:
  title: Post API
  description: |-
    This is a simple post API, including creating, reading, updating and deleting posts.
  version: 1.0.0
tags:
  - name: post
    description: Everything about your post
paths:
  /post:
    post:
      tags:
        - post
      summary: Add a new Post
      description: Add a new Post
      requestBody:
        $ref: '#/components/requestBodies/AddPost'
      responses:
        '201':
          description: Successful created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostPut'
        '400':
          description: Incorrect format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseWithError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - bearerAuth: []
  /posts:
    get:
      tags:
        - post
      summary: Get all Posts
      description: Get all Posts ordered by created date
      responses:
        '200':
          description: Successful operation & a list of Posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - bearerAuth: []
  /author/{user_id}/posts:
    get:
      tags:
        - post
      summary: Find Post by UserId
      description: Returns a single Post
      parameters:
        - name: user_id
          in: path
          description: ID of Post to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - bearerAuth: []
  /post/{post_id}:
    get:
      tags:
        - post
      summary: Find Post by PostId
      description: Returns a single Post
      parameters:
        - name: post_id
          in: path
          description: ID of Post to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - bearerAuth: []
    put:
      tags:
        - post
      summary: Update an existing Post
      description: Update an existing Post by Id
      parameters:
        - name: post_id
          in: path
          description: ID of Post to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        $ref: '#/components/requestBodies/PutModifyPost'
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostPut'
        '400':
          description: Incorrect format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseWithError'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - bearerAuth: []
    delete:
      tags:
        - post
      summary: Deletes a Post
      description: Delete a Post
      parameters:
        - name: post_id
          in: path
          description: PostId to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - bearerAuth: []
components:
  schemas:
    Post:
      type: object
      properties:
        post_id: 
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        user:
          type: object
          properties:
            user_id:
              type: string
              format: uuid
            name:
              type: string
    PostPut:
      type: object
      properties:
        post_id: 
          type: string
          format: uuid
        message:
          type: string
    User:
      type: object
      properties:
        user_id: 
          type: string
          format: uuid
        name:
          type: string
        post:
          type: array
          items:
            type: object
            properties:
              post_id:
                type: string
                format: uuid
              title:
                type: string
              content:
                type: string
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
    PostRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        user_id:
          type: string
          format: uuid
    PutRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
    GenericResponse:
      type: object
      properties:
        success:
          type: boolean
          default: false
        statusCode:
          type: number
        errorCode:
          type: number
        message:
          type: string
    GenericResponseWithError:
      type: object
      properties:
        success:
          type: boolean
          default: false
        statusCode:
          type: number
        errorCode:
          type: number
        message:
          type: string
        errors:
          type: object
  requestBodies:
    AddPost:
      description: Post object to be added
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostRequest'
    ModifyPost:
      description: Post object to be modified
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostRequest'
    PutModifyPost:
      description: Post object to be modified
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PutRequest'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer